spring.application.name=app-web-finanzas-personales-prueba

spring.config.import=optional:file:.env[.properties]

# ---------------------------------
# MySQL
# ---------------------------------
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ===============================
# JPA / HIBERNATE
# ===============================
# para desarrollo
spring.jpa.hibernate.ddl-auto=create-drop
# para produccion 
#spring.jpa.hibernate.ddl-auto=validate

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# SECURITY
# ===============================
# Desactivar login por defecto de Spring
spring.security.user.name=disabled
spring.security.user.password=disabled

# ---------------------------------
# RECHAZA CAMPOS DESCONOCIDOS GLOBALMENTE
# ---------------------------------
spring.jackson.deserialization.fail-on-unknown-properties=true
# ---------------------------------
# JWT
# ---------------------------------
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

# ===============================
# DEBUG
# ===============================
#logging.level.org.springframework.boot.context.config=TRACE
#logging.level.com.zaxxer.hikari=DEBUG

#logging.level.org.springframework.web=#DEBUG
#logging.level.io.jsonwebtoken=DEBUG